### ISSUE TITLE
Transcribe Error

### ISSUE THREAD

**Issue by lightyrs** [antiboredom/audiogrep#2]
On Mac OS X Yosemite, homebrew python version 2.7.9 ——

```
python audiogrep.py --input /Users/harris/Documents/Books/The\ War\ of\ Art\ -\ Steven\ Pressfield/02\ -\ Book\ One\ -\ Resistance\,\ Defining\ the\ Enemy/22\ -\ Resistance\ and\ Sex.mp3 --transcribe
ffmpeg version 2.5.4 Copyright (c) 2000-2015 the FFmpeg developers
  built on Feb 16 2015 16:34:55 with Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/2.5.4 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-libx264 --enable-libmp3lame --enable-libvo-aacenc --enable-libxvid --enable-libvorbis --enable-libvpx --enable-vda
  libavutil      54. 15.100 / 54. 15.100
  libavcodec     56. 13.100 / 56. 13.100
  libavformat    56. 15.102 / 56. 15.102
  libavdevice    56.  3.100 / 56.  3.100
  libavfilter     5.  2.103 /  5.  2.103
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  3.100 / 53.  3.100
[mp3 @ 0x7ff26200da00] Estimating duration from bitrate, this may be inaccurate
Input #0, mp3, from '/Users/harris/Documents/Books/The War of Art - Steven Pressfield/02 - Book One - Resistance, Defining the Enemy/22 - Resistance and Sex.mp3':
  Metadata:
    album           : The War of Art
    genre           : Other
    album_artist    : Steven Pressfield
    track           : 22
    artist          : Steven Pressfield
  Duration: 00:01:05.78, start: 0.000000, bitrate: 201 kb/s
    Stream #0:0: Audio: mp3, 44100 Hz, stereo, s16p, 192 kb/s
    Stream #0:1: Video: mjpeg, yuvj444p(pc, bt470bg/unknown/unknown), 680x680, 90k tbr, 90k tbn, 90k tbc
    Metadata:
      title           :
      comment         : Other
Output #0, wav, to '/Users/harris/Documents/Books/The War of Art - Steven Pressfield/02 - Book One - Resistance, Defining the Enemy/22 - Resistance and Sex.mp3.temp.wav':
  Metadata:
    IPRD            : The War of Art
    IGNR            : Other
    album_artist    : Steven Pressfield
    IPRT            : 22
    IART            : Steven Pressfield
    ISFT            : Lavf56.15.102
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 16000 Hz, mono, s16, 256 kb/s
    Metadata:
      encoder         : Lavc56.13.100 pcm_s16le
Stream mapping:
  Stream #0:0 -> #0:0 (mp3 (native) -> pcm_s16le (native))
Press [q] to stop, [?] for help
size=    2056kB time=00:01:05.77 bitrate= 256.0kbits/s
video:0kB audio:2056kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.007316%
1/1 Transcribing /Users/harris/Documents/Books/The War of Art - Steven Pressfield/02 - Book One - Resistance, Defining the Enemy/22 - Resistance and Sex.mp3.temp.wav
Traceback (most recent call last):
  File "audiogrep.py", line 208, in <module>
    transcribe(files)
  File "audiogrep.py", line 35, in transcribe
    transcript = subprocess.check_output(['pocketsphinx_continuous', '-infile', f, '-time', 'yes', '-logfn', '/dev/null', '-vad_prespeech', str(pre), '-vad_postspeech', str(post)])
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

This happens with any .mp3 file I attempt to transcribe.

**Comment by nwoeanhinnogaehr** [comment]
Installing pocketsphinx fixed this for me.

**Comment by antiboredom** [comment]
Glad to hear!
