### ISSUE TITLE
--Transcribe fails

### ISSUE THREAD

**Issue by justindachille** [antiboredom/audiogrep#28]
Fresh install, Mac Mojave 10.14.4, Python 2.7
I uninstalled and reinstalled pocketsphinx with the mac instructions and got the same error, continuous test seems to work fine. 

```
audiogrep --input test.mp3 --transcribe


test.mp3.temp.wav
ffmpeg version 4.1.3 Copyright (c) 2000-2019 the FFmpeg developers
  built with Apple LLVM version 10.0.1 (clang-1001.0.46.4)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.1.3_1 --enable-shared --enable-pthreads --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags='-I/Library/Java/JavaVirtualMachines/adoptopenjdk-11.0.2.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/adoptopenjdk-11.0.2.jdk/Contents/Home/include/darwin' --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libmp3lame --enable-libopus --enable-librubberband --enable-libsnappy --enable-libtesseract --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-videotoolbox --disable-libjack --disable-indev=jack --enable-libaom --enable-libsoxr
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Input #0, mp3, from 'test.mp3':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    encoder         : Lavf57.56.101
  Duration: 00:05:06.94, start: 0.025057, bitrate: 192 kb/s
    Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 192 kb/s
    Metadata:
      encoder         : Lavc57.64
Stream mapping:
  Stream #0:0 -> #0:0 (mp3 (mp3float) -> pcm_s16le (native))
Press [q] to stop, [?] for help
Output #0, wav, to 'test.mp3.temp.wav':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    ISFT            : Lavf58.20.100
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 16000 Hz, mono, s16, 256 kb/s
    Metadata:
      encoder         : Lavc58.35.100 pcm_s16le
size=    9591kB time=00:05:06.89 bitrate= 256.0kbits/s speed= 456x
video:0kB audio:9591kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000794%
1/1 Transcribing test.mp3.temp.wav
ERROR: "cmd_ln.c", line 942: Unknown argument: -alignctl

File "/usr/local/bin/audiogrep", line 6, in <module>
    audiogrep.main()
  File "/Library/Python/2.7/site-packages/audiogrep/audiogrep.py", line 392, in main
    transcribe(files)
  File "/Library/Python/2.7/site-packages/audiogrep/audiogrep.py", line 43, in transcribe
    transcript = subprocess.check_output(['pocketsphinx_continuous', '-infile', f, '-time', 'yes', '-logfn', '/dev/null', '-vad_prespeech', str(pre), '-vad_postspeech', str(post)])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 567, in check_output
    output, unused_err = process.communicate()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 791, in communicate
    stdout = _eintr_retry_call(self.stdout.read)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
```

**Comment by pierow2k** [comment]
@justindachille - Did you find a solution for this?  I am also receiving this error using Alpine.  The same build process has worked previously which makes me wonder if something in the CMU Sphinx packages has changed. (Though the regression tests for pocketsphinx all seem to pass)

```
ERROR: "cmd_ln.c", line 942: Unknown argument: -alignctl
Traceback (most recent call last):
  File "/usr/bin/audiogrep", line 6, in <module>
    audiogrep.main()
  File "/usr/lib/python3.6/site-packages/audiogrep/audiogrep.py", line 392, in main
    transcribe(files)
  File "/usr/lib/python3.6/site-packages/audiogrep/audiogrep.py", line 43, in transcribe
    transcript = subprocess.check_output(['pocketsphinx_continuous', '-infile', f, '-time', 'yes', '-logfn', '/dev/null', '-vad_prespeech', str(pre), '-vad_postspeech', str(post)])
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 425, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.6/subprocess.py", line 850, in communicate
    stdout = self.stdout.read()
```
