### ISSUE TITLE
Output supercut files are 0 bytes

### ISSUE THREAD

**Issue by OisinMoran** [antiboredom/audiogrep#9]
Audiogrep transcribes the audio files seemingly correctly and when creating a supercut gives many instances of the searched word but the final result is a `supercut.mp3` that is 0 bytes. 
Currently running this on Linux

**Comment by colinsullivan** [comment]
Same symptom for me.

In the `compose` function, there is a giant try block which catches all errors and silently fails:

https://github.com/antiboredom/audiogrep/blob/master/audiogrep.py#L159-187

Removing this, I can see that when I try the examples, there is an error coming from within pydub:

    Traceback (most recent call last):
      File "./audiogrep/audiogrep.py", line 243, in <module>
        compose(segments, out=args.outputfile, padding=args.padding, crossfade=args.crossfade, layer=args.layer)
      File "./audiogrep/audiogrep.py", line 164, in compose
        files[f] = AudioSegment.from_wav(f)
      File "/usr/local/lib/python2.7/site-packages/pydub/audio_segment.py", line 367, in from_wav
        return cls.from_file(file, 'wav')
      File "/usr/local/lib/python2.7/site-packages/pydub/audio_segment.py", line 342, in from_file
        raise CouldntDecodeError("Decoding failed. ffmpeg returned error code: {0}".format(retcode))
    pydub.exceptions.CouldntDecodeError: Decoding failed. ffmpeg returned error code: 1

Was able to debug a bit within pydub, but not much.

It would be nice to try this out!
